### ISSUE TITLE
Logging: CLI options for setting format and output

### ISSUE THREAD

**Issue by jo-bru** [Interactions-HSG/xarm-grpc#23]
Add CLI options to be able to format and define output (e.g. Logfile) for logging information.

By setting a logging destination, the additional information (info, debug, eval) can be retrieved from an external file if the xarm-commander is used in an integrated way (e.g. called by Nodejs).

**Comment by jo-bru** [comment]
This will later be probably defined as an option for the `server` command (see #18).

**Comment by iomz** [comment]
Likewise #17, this will be done via gRPC.
