### ISSUE TITLE
SWIG: Function Overloading

### ISSUE THREAD

**Issue by jo-bru** [Interactions-HSG/xarm-grpc#3]
Implement 2nd solution for overloaded functions: using `%rename` to support overloaded functions.
See [corresponding section](https://github.com/Interactions-HSG/xarm-commander/blob/d8bed6b014cbf24bca08468b8eb5a4b92f5809fd/swig/xarm.i#L46)

**Comment by iomz** [comment]
SWIG is no longer relevant. Closing.
